{
 "title": "Métricas Genéricas (Ruins)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Produtos adicionados ao Carrinho (Ruim)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "rate(cart_additions_total[1m])", "legendFormat": "Total Adições" }
   ]
  },
  {
   "title": "Início de Checkout (Ruim)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "rate(checkout_start_total[1m])", "legendFormat": "Total Checkout" }
   ]
  },
  {
   "title": "Tentativas de Pagamento (Ruim)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(payment_attempts_total[1m])",
     "legendFormat": "Total Tentativas"
    }
   ]
  },
  {
   "title": "Falhas de Pagamento (Ruim)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(payment_failures_total[1m])",
     "legendFormat": "Total Falhas"
    }
   ]
  },
  {
   "title": "Compras Finalizadas (Ruim)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(purchase_completed_total[1m])",
     "legendFormat": "Total Sucessos"
    }
   ]
  }
 ]
}